FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Копируем весь исходный код проекта
COPY . .

# Собираем проект (если используется сборка)
RUN npm run build

# Устанавливаем легкий веб-сервер для раздачи статики
RUN npm install -g serve

# Указываем порт, который будет использоваться
EXPOSE 3000

# Команда для запуска приложения
CMD ["serve", "-s", "build", "-l", "3000"]