# Стадия 1: Сборка приложения
FROM node:18-alpine as builder

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальной код приложения
COPY . .

# Собираем приложение
RUN npm run build

# Стадия 2: Настройка Nginx и запуск
FROM nginx:alpine

# Копируем собранные файлы из предыдущей стадии
COPY --from=builder /app/build /usr/share/nginx/html

# Копируем кастомную конфигурацию Nginx (если нужно)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# Открываем порт 80
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]