FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

# Копируем остальной код приложения
COPY . .

# Собираем приложение
RUN npm run build

# Стадия 2: Настройка Nginx и запуск
FROM nginx:alpine

# Копируем собранные файлы из предыдущей стадии
COPY --from=builder /app/dist /usr/share/nginx/html

# Копируем кастомную конфигурацию Nginx (если нужно)
# COPY nginx.conf /etc/nginx/conf.d/default.conf
 
# Открываем порт 80
EXPOSE 80

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]