FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Устанавливаем легкий веб-сервер для раздачи статики
RUN npm install -g serve

# Указываем порт, который будет использоваться
EXPOSE 3000

# Команда для запуска приложения
CMD ["serve", "-s", "build", "-l", "3000"]