FROM node:20-alpine AS builder

WORKDIR /app
COPY package.json ./
COPY package-lock.json* ./
RUN npm install
COPY src ./src
COPY . .
RUN npm run build

# Финальный этап: только результат сборки
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
# Здесь node_modules не копируется, он остался в этапе builder

EXPOSE 3000
CMD ["npx", "serve", "-s", "dist"]