FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

ENV UV_COMPILE_BYTECODE=1

ENV UV_LINK_MODE=copy

ADD . /app

RUN uv sync --frozen --no-dev

RUN uv install fastapi-cli

ENV PATH="/app/.venv/bin:$PATH"

ENTRYPOINT []

CMD ["fastapi", "dev", "--host", "0.0.0.0", "--port", "8000"]