networks:
  app-network:
    driver: bridge

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/app:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:8000"
    depends_on:
      - backend
    networks:
      - app-network