version: '1.0'

services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/app

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend