version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/app

  frontend:
    build: ./frontend
    ports:
      - "8080:8000"
    depends_on:
      - backend