version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/app:/app

  frontend:
    build: ./frontend
    ports:
      - "80:80"

# Слева: Порт хоста (ваша машина, например, 3000 или 80).
# Справа: Порт контейнера (внутри контейнера, например, 3000 или 8000).

