FROM python:3.12-slim-bookworm
# RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.local/bin/:$PATH"

WORKDIR /app

COPY pyproject.toml requirements.txt uv.lock ./

RUN uv sync

COPY . .

CMD ["uv", "run", "fastapi", "dev"]