# Используем официальный образ Python как базовый
FROM python:3.11-slim

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем uv
RUN pip install --no-cache-dir uv

# Копируем только файлы зависимостей
COPY pyproject.toml uv.lock ./

# Создаем проект с uv и устанавливаем зависимости
RUN uv init && \
    uv sync

# Копируем остальной код приложения
COPY . .

# Указываем команду для запуска (использует uv для запуска Python)
CMD ["uv", "run", "python", "main.py"]